-- REFERENCE ONLY — NOT EXECUTABLE SOURCE OF TRUTH
--
-- Official migrations (apply in order via Supabase SQL Editor or supabase db push):
--   1. supabase/migrations/20260719153000_analytics_events_storage_schema_v1.sql
--   2. supabase/migrations/20260719153001_analytics_events_storage_security_v1.sql
--
-- Canonical documentation:
--   docs/analytics/ANALYTICS_SCHEMA.md
--
-- Read-only validation:
--   docs/analytics/analytics-events-schema-inspection.sql
--   docs/analytics/analytics-events-schema-preflight.sql
--
-- Do not edit SQL in this file. Edit only supabase/migrations/*.sql
