/**
 * PATCH 10.4 — Anti-Regret Foundation taxonomies (observational only).
 *
 * Signals describe evidence quality — not happiness, satisfaction, or confirmed regret.
 */

export const MIA_ANTI_REGRET_FOUNDATION_CATALOG_VERSION = "10.4.0";

export const MIA_ANTI_REGRET_SIGNAL_POLARITY = Object.freeze({
  POSITIVE_SIGNAL: "POSITIVE_SIGNAL",
  NEUTRAL_SIGNAL: "NEUTRAL_SIGNAL",
  UNCERTAIN_SIGNAL: "UNCERTAIN_SIGNAL",
  NEGATIVE_SIGNAL: "NEGATIVE_SIGNAL",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ANTI_REGRET_SIGNAL_SOURCE = Object.freeze({
  ACCEPTANCE_SIGNAL: "ACCEPTANCE_SIGNAL",
  REJECTION_SIGNAL: "REJECTION_SIGNAL",
  ALTERNATIVE_REQUEST: "ALTERNATIVE_REQUEST",
  SECOND_BEST: "SECOND_BEST",
  PRICE_ALERT: "PRICE_ALERT",
  FAVORITE: "FAVORITE",
  OFFER_CLICK: "OFFER_CLICK",
  CONSTRAINT_CHANGE: "CONSTRAINT_CHANGE",
  FOLLOW_UP: "FOLLOW_UP",
  MULTI_TURN: "MULTI_TURN",
  DECISION_CONTEXT: "DECISION_CONTEXT",
  PRICE_INTELLIGENCE: "PRICE_INTELLIGENCE",
  SAVINGS_ESTIMATION: "SAVINGS_ESTIMATION",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ANTI_REGRET_CONFIDENCE = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ANTI_REGRET_OBSERVED_PATTERN = Object.freeze({
  DIRECT_ACCEPTANCE: "DIRECT_ACCEPTANCE",
  COMPARISON_BEFORE_ACCEPTANCE: "COMPARISON_BEFORE_ACCEPTANCE",
  MULTIPLE_REJECTIONS: "MULTIPLE_REJECTIONS",
  PRICE_WAITING: "PRICE_WAITING",
  MULTIPLE_CONSTRAINT_CHANGES: "MULTIPLE_CONSTRAINT_CHANGES",
  LONG_EXPLORATION: "LONG_EXPLORATION",
  UNKNOWN: "UNKNOWN",
});

/** Score bounds — internal analytics only; never shown to users */
export const MIA_ANTI_REGRET_SCORE_MIN = 0;
export const MIA_ANTI_REGRET_SCORE_MAX = 100;
export const MIA_ANTI_REGRET_SCORE_NEUTRAL_BASE = 50;
