/**
 * PATCH 7.3 — Latency stage taxonomy (stable server-side pipeline stages).
 */

export const MIA_LATENCY_STAGES = Object.freeze({
  HTTP_VALIDATION: "HTTP_VALIDATION",
  AUTH: "AUTH",
  ROUTER: "ROUTER",
  INTENT_CLASSIFICATION: "INTENT_CLASSIFICATION",
  DATA_LAYER: "DATA_LAYER",
  DECISION_ENGINE: "DECISION_ENGINE",
  PROVIDER: "PROVIDER",
  LLM: "LLM",
  CONTRACTS: "CONTRACTS",
  RESPONSE_BUILDER: "RESPONSE_BUILDER",
  TOTAL: "TOTAL",
});

/** Ordered pipeline segments for exclusive duration derivation (when marked). */
export const MIA_LATENCY_STAGE_ORDER = Object.freeze([
  MIA_LATENCY_STAGES.HTTP_VALIDATION,
  MIA_LATENCY_STAGES.AUTH,
  MIA_LATENCY_STAGES.ROUTER,
  MIA_LATENCY_STAGES.INTENT_CLASSIFICATION,
  MIA_LATENCY_STAGES.DATA_LAYER,
  MIA_LATENCY_STAGES.DECISION_ENGINE,
  MIA_LATENCY_STAGES.PROVIDER,
  MIA_LATENCY_STAGES.LLM,
  MIA_LATENCY_STAGES.CONTRACTS,
  MIA_LATENCY_STAGES.RESPONSE_BUILDER,
]);

export const MIA_LATENCY_STAGE_STATUSES = Object.freeze({
  OK: "ok",
  SKIPPED: "skipped",
  FAILED: "failed",
  UNAVAILABLE: "unavailable",
});

export const MIA_LATENCY_BANDS = Object.freeze({
  FAST: "FAST",
  ACCEPTABLE: "ACCEPTABLE",
  SLOW: "SLOW",
  CRITICAL: "CRITICAL",
});

/** Documented baseline thresholds (not SLO enforcement). */
export const MIA_LATENCY_THRESHOLD_MS = Object.freeze({
  FAST: 2000,
  ACCEPTABLE: 5000,
  SLOW: 10000,
});
