/**
 * PATCH 8.2 — Provider Attempt Analytics taxonomies
 */

export const MIA_PROVIDER_ATTEMPT_CATALOG_VERSION = "8.2.0";

export const MIA_PROVIDER_FAMILIES = Object.freeze({
  MARKETPLACE: "MARKETPLACE",
  SEARCH_ENGINE: "SEARCH_ENGINE",
  CACHE: "CACHE",
  SCRAPER: "SCRAPER",
  DATA_PROVIDER: "DATA_PROVIDER",
  OTHER: "OTHER",
  UNKNOWN: "UNKNOWN",
});

export const MIA_PROVIDER_RUNTIME_MODES = Object.freeze({
  LEGACY: "LEGACY",
  CONTROLLED: "CONTROLLED",
  SHADOW: "SHADOW",
  UNKNOWN: "UNKNOWN",
});

export const MIA_PROVIDER_EXECUTION_PATHS = Object.freeze({
  LEGACY_CHAIN: "LEGACY_CHAIN",
  CONTROLLED_MULTI_PROVIDER: "CONTROLLED_MULTI_PROVIDER",
  SHADOW_ONLY: "SHADOW_ONLY",
  UNKNOWN: "UNKNOWN",
});

export const MIA_PROVIDER_CONFIG_STATUSES = Object.freeze({
  ENABLED: "ENABLED",
  DISABLED: "DISABLED",
  STUB: "STUB",
  UNKNOWN: "UNKNOWN",
});

export const MIA_PROVIDER_ATTEMPT_STATUSES = Object.freeze({
  SUCCESS: "SUCCESS",
  EMPTY: "EMPTY",
  FAILED: "FAILED",
  TIMEOUT: "TIMEOUT",
  SKIPPED: "SKIPPED",
  CANCELLED: "CANCELLED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_PROVIDER_SKIP_REASONS = Object.freeze({
  DISABLED: "DISABLED",
  NOT_ELIGIBLE: "NOT_ELIGIBLE",
  SHORT_CIRCUIT: "SHORT_CIRCUIT",
  DATA_LAYER_RESOLVED: "DATA_LAYER_RESOLVED",
  RUNTIME_RULE: "RUNTIME_RULE",
  MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
  CIRCUIT_OPEN: "CIRCUIT_OPEN",
  UNKNOWN: "UNKNOWN",
  NOT_APPLICABLE: "NOT_APPLICABLE",
});

export const MIA_PROVIDER_FAILURE_CATEGORIES = Object.freeze({
  AUTHENTICATION: "AUTHENTICATION",
  AUTHORIZATION: "AUTHORIZATION",
  RATE_LIMIT: "RATE_LIMIT",
  NETWORK: "NETWORK",
  TIMEOUT: "TIMEOUT",
  PROVIDER_RESPONSE: "PROVIDER_RESPONSE",
  CONTRACT: "CONTRACT",
  PARSING: "PARSING",
  CONFIGURATION: "CONFIGURATION",
  INTERNAL: "INTERNAL",
  UNKNOWN: "UNKNOWN",
  NOT_APPLICABLE: "NOT_APPLICABLE",
});

export const MIA_PROVIDER_HTTP_STATUS_GROUPS = Object.freeze({
  XX2: "2XX",
  XX3: "3XX",
  XX4: "4XX",
  XX5: "5XX",
  NETWORK: "NETWORK",
  NOT_APPLICABLE: "NOT_APPLICABLE",
  UNKNOWN: "UNKNOWN",
});