/**
 * PATCH 9.2 — Recommendation Acceptance Signal taxonomies
 */

export const MIA_RECOMMENDATION_ACCEPTANCE_CATALOG_VERSION = "9.2.0";

export const MIA_ACCEPTANCE_SIGNAL_TYPES = Object.freeze({
  RECOMMENDATION_RENDERED: "RECOMMENDATION_RENDERED",
  WINNER_OFFER_CLICKED: "WINNER_OFFER_CLICKED",
  ALTERNATIVE_OFFER_CLICKED: "ALTERNATIVE_OFFER_CLICKED",
  PRODUCT_FAVORITED: "PRODUCT_FAVORITED",
  PRICE_ALERT_CREATED: "PRICE_ALERT_CREATED",
  WINNER_FOLLOW_UP: "WINNER_FOLLOW_UP",
  PRODUCT_DETAIL_REQUESTED: "PRODUCT_DETAIL_REQUESTED",
  PRICE_REQUESTED: "PRICE_REQUESTED",
  STORE_REQUESTED: "STORE_REQUESTED",
  LINK_REQUESTED: "LINK_REQUESTED",
  COMPARISON_REQUESTED: "COMPARISON_REQUESTED",
  RECOMMENDATION_REVISITED: "RECOMMENDATION_REVISITED",
  PURCHASE_CONFIRMED: "PURCHASE_CONFIRMED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ACCEPTANCE_SIGNAL_STRENGTHS = Object.freeze({
  WEAK: "WEAK",
  MEDIUM: "MEDIUM",
  STRONG: "STRONG",
  CONFIRMED: "CONFIRMED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ACCEPTANCE_SIGNAL_TARGETS = Object.freeze({
  WINNER: "WINNER",
  RUNNER_UP: "RUNNER_UP",
  ALTERNATIVE: "ALTERNATIVE",
  OFFER_ONLY: "OFFER_ONLY",
  DECISION_GENERIC: "DECISION_GENERIC",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ACCEPTANCE_SIGNAL_SOURCES = Object.freeze({
  CLIENT_INTERACTION: "CLIENT_INTERACTION",
  SERVER_CONVERSATION: "SERVER_CONVERSATION",
  FRONTEND_RENDER: "FRONTEND_RENDER",
  SYSTEM_CONFIRMATION: "SYSTEM_CONFIRMATION",
  DERIVED_SQL: "DERIVED_SQL",
  UNKNOWN: "UNKNOWN",
});

export const MIA_ACCEPTANCE_CORRELATION_METHODS = Object.freeze({
  REQUEST_ID: "REQUEST_ID",
  SESSION_PRODUCT_WINDOW: "SESSION_PRODUCT_WINDOW",
  SESSION_SEQUENCE: "SESSION_SEQUENCE",
  UNRESOLVED: "UNRESOLVED",
});

export const MIA_ACCEPTANCE_CORRELATION_CONFIDENCE = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNRESOLVED: "UNRESOLVED",
});

/** Official temporal buckets — shared by SQL and runtime classification */
export const MIA_ACCEPTANCE_TIME_BUCKETS = Object.freeze({
  SAME_TURN: "same_turn",
  UP_TO_1_MIN: "up_to_1_min",
  UP_TO_5_MIN: "up_to_5_min",
  UP_TO_30_MIN: "up_to_30_min",
  SAME_SESSION: "same_session",
  LATER: "later",
  UNKNOWN: "unknown",
});

export const MIA_ACCEPTANCE_SESSION_PRODUCT_WINDOW_MS = 30 * 60 * 1000;
export const MIA_ACCEPTANCE_SAME_TURN_MS = 90 * 1000;
export const MIA_ACCEPTANCE_ONE_MINUTE_MS = 60 * 1000;
export const MIA_ACCEPTANCE_FIVE_MINUTES_MS = 5 * 60 * 1000;
