/**
 * PATCH 9.3 — Recommendation Rejection / Abandonment signal taxonomies
 */

export const MIA_RECOMMENDATION_REJECTION_CATALOG_VERSION = "9.3.0";

export const MIA_REJECTION_SIGNAL_TYPES = Object.freeze({
  EXPLICIT_REJECTION: "EXPLICIT_REJECTION",
  PRICE_REJECTION: "PRICE_REJECTION",
  BRAND_REJECTION: "BRAND_REJECTION",
  FEATURE_REJECTION: "FEATURE_REJECTION",
  CATEGORY_REJECTION: "CATEGORY_REJECTION",
  CONDITION_REJECTION: "CONDITION_REJECTION",
  TRUST_REJECTION: "TRUST_REJECTION",
  ALTERNATIVE_REQUESTED: "ALTERNATIVE_REQUESTED",
  CONSTRAINT_REFINEMENT: "CONSTRAINT_REFINEMENT",
  BUDGET_REFINEMENT: "BUDGET_REFINEMENT",
  BRAND_REFINEMENT: "BRAND_REFINEMENT",
  FEATURE_REFINEMENT: "FEATURE_REFINEMENT",
  NEW_SEARCH_STARTED: "NEW_SEARCH_STARTED",
  WINNER_REPLACED: "WINNER_REPLACED",
  DECISION_SUPERSEDED: "DECISION_SUPERSEDED",
  PURCHASE_POSTPONED: "PURCHASE_POSTPONED",
  PURCHASE_ABANDONED_EXPLICITLY: "PURCHASE_ABANDONED_EXPLICITLY",
  COMMERCIAL_FLOW_EXITED: "COMMERCIAL_FLOW_EXITED",
  SESSION_ABANDONED_OBSERVED: "SESSION_ABANDONED_OBSERVED",
  NO_FURTHER_EVIDENCE: "NO_FURTHER_EVIDENCE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_REJECTION_SIGNAL_CLASSES = Object.freeze({
  REJECTION: "REJECTION",
  REFINEMENT: "REFINEMENT",
  SUBSTITUTION: "SUBSTITUTION",
  POSTPONEMENT: "POSTPONEMENT",
  ABANDONMENT: "ABANDONMENT",
  INCONCLUSIVE: "INCONCLUSIVE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_REJECTION_EVIDENCE_STRENGTHS = Object.freeze({
  EXPLICIT: "EXPLICIT",
  STRONG: "STRONG",
  MODERATE: "MODERATE",
  WEAK: "WEAK",
  INCONCLUSIVE: "INCONCLUSIVE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_REJECTION_SIGNAL_TARGETS = Object.freeze({
  WINNER: "WINNER",
  RUNNER_UP: "RUNNER_UP",
  ALTERNATIVE: "ALTERNATIVE",
  OFFER: "OFFER",
  DECISION_GENERIC: "DECISION_GENERIC",
  COMMERCIAL_FLOW: "COMMERCIAL_FLOW",
  UNKNOWN: "UNKNOWN",
});

export const MIA_REJECTION_SIGNAL_REASONS = Object.freeze({
  PRICE: "PRICE",
  BRAND: "BRAND",
  FEATURE: "FEATURE",
  PERFORMANCE: "PERFORMANCE",
  BATTERY: "BATTERY",
  CAMERA: "CAMERA",
  SIZE: "SIZE",
  DESIGN: "DESIGN",
  OPERATING_SYSTEM: "OPERATING_SYSTEM",
  STORAGE: "STORAGE",
  CONDITION: "CONDITION",
  AVAILABILITY: "AVAILABILITY",
  MERCHANT: "MERCHANT",
  TRUST: "TRUST",
  CATEGORY: "CATEGORY",
  COMPATIBILITY: "COMPATIBILITY",
  OTHER_OBSERVED: "OTHER_OBSERVED",
  NOT_APPLICABLE: "NOT_APPLICABLE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_REJECTION_SIGNAL_OUTCOMES = Object.freeze({
  DECISION_RETAINED: "DECISION_RETAINED",
  WINNER_RETAINED: "WINNER_RETAINED",
  WINNER_REPLACED: "WINNER_REPLACED",
  ALTERNATIVE_SELECTED: "ALTERNATIVE_SELECTED",
  NEW_DECISION_CREATED: "NEW_DECISION_CREATED",
  FLOW_CONTINUED: "FLOW_CONTINUED",
  FLOW_EXITED: "FLOW_EXITED",
  PURCHASE_POSTPONED: "PURCHASE_POSTPONED",
  ABANDONMENT_OBSERVED: "ABANDONMENT_OBSERVED",
  UNRESOLVED: "UNRESOLVED",
});

export const MIA_REJECTION_SIGNAL_SOURCES = Object.freeze({
  SERVER_CONVERSATION: "SERVER_CONVERSATION",
  CLIENT_INTERACTION: "CLIENT_INTERACTION",
  DECISION_TRANSITION: "DECISION_TRANSITION",
  SESSION_LIFECYCLE: "SESSION_LIFECYCLE",
  DERIVED_SQL: "DERIVED_SQL",
  SYSTEM_EVENT: "SYSTEM_EVENT",
  UNKNOWN: "UNKNOWN",
});

export const MIA_REJECTION_CORRELATION_METHODS = Object.freeze({
  REQUEST_ID: "REQUEST_ID",
  SESSION_PRODUCT_WINDOW: "SESSION_PRODUCT_WINDOW",
  SESSION_SEQUENCE: "SESSION_SEQUENCE",
  DECISION_TRANSITION: "DECISION_TRANSITION",
  SESSION_LIFECYCLE: "SESSION_LIFECYCLE",
  UNRESOLVED: "UNRESOLVED",
});

export const MIA_REJECTION_CORRELATION_CONFIDENCE = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNRESOLVED: "UNRESOLVED",
});

/** Shared temporal buckets with PATCH 9.2 */
export const MIA_REJECTION_TIME_BUCKETS = Object.freeze({
  SAME_TURN: "same_turn",
  UP_TO_1_MIN: "up_to_1_min",
  UP_TO_5_MIN: "up_to_5_min",
  UP_TO_30_MIN: "up_to_30_min",
  SAME_SESSION: "same_session",
  NEXT_SESSION: "next_session",
  LATER: "later",
  UNKNOWN: "unknown",
});

export const MIA_REJECTION_SAME_TURN_MS = 90 * 1000;
export const MIA_REJECTION_ONE_MINUTE_MS = 60 * 1000;
export const MIA_REJECTION_FIVE_MINUTES_MS = 5 * 60 * 1000;
export const MIA_REJECTION_SESSION_WINDOW_MS = 30 * 60 * 1000;
