/**
 * PATCH 10.2 — Savings Estimation taxonomies (observational only).
 */

export const MIA_SAVINGS_ESTIMATION_CATALOG_VERSION = "10.2.0";

export const MIA_SAVINGS_TYPE = Object.freeze({
  OBSERVED: "OBSERVED",
  ESTIMATED: "ESTIMATED",
  UNVERIFIED: "UNVERIFIED",
  VERIFIED: "VERIFIED",
  UNKNOWN: "UNKNOWN",
});

export const MIA_SAVINGS_BASELINE_TYPE = Object.freeze({
  MINIMUM_OFFER: "MINIMUM_OFFER",
  MEDIAN_OFFER: "MEDIAN_OFFER",
  AVERAGE_OFFER: "AVERAGE_OFFER",
  WINNER_OFFER: "WINNER_OFFER",
  ORIGINAL_PRICE: "ORIGINAL_PRICE",
  PROMOTIONAL_REFERENCE: "PROMOTIONAL_REFERENCE",
  ALERT_TARGET: "ALERT_TARGET",
  ESTIMATED_UI_ASSUMPTION: "ESTIMATED_UI_ASSUMPTION",
  HISTORICAL_PRICE: "HISTORICAL_PRICE",
  PURCHASE_PRICE: "PURCHASE_PRICE",
  NONE: "NONE",
  UNKNOWN: "UNKNOWN",
});

/** Reserved — not emitted until architecture supports them */
export const MIA_SAVINGS_BASELINE_RESERVED = Object.freeze([
  MIA_SAVINGS_BASELINE_TYPE.HISTORICAL_PRICE,
  MIA_SAVINGS_BASELINE_TYPE.PURCHASE_PRICE,
  MIA_SAVINGS_BASELINE_TYPE.ALERT_TARGET,
]);

export const MIA_SAVINGS_CALCULATION_METHOD = Object.freeze({
  WINNER_VS_MINIMUM: "WINNER_VS_MINIMUM",
  WINNER_VS_MEDIAN: "WINNER_VS_MEDIAN",
  WINNER_VS_AVERAGE: "WINNER_VS_AVERAGE",
  PROMOTIONAL_VS_ORIGINAL: "PROMOTIONAL_VS_ORIGINAL",
  CURRENT_VS_ALERT_TARGET: "CURRENT_VS_ALERT_TARGET",
  PERCENTAGE_ASSUMPTION: "PERCENTAGE_ASSUMPTION",
  HISTORICAL_COMPARISON: "HISTORICAL_COMPARISON",
  PURCHASE_COMPARISON: "PURCHASE_COMPARISON",
  NO_CALCULATION: "NO_CALCULATION",
  UNKNOWN: "UNKNOWN",
});

export const MIA_SAVINGS_CONFIDENCE = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNKNOWN: "UNKNOWN",
});

export const MIA_SAVINGS_NATURE = Object.freeze({
  OFFER_DIFFERENCE: "OFFER_DIFFERENCE",
  ADVERTISED_DISCOUNT: "ADVERTISED_DISCOUNT",
  POTENTIAL_SAVINGS: "POTENTIAL_SAVINGS",
  ESTIMATED_SAVINGS: "ESTIMATED_SAVINGS",
  ALERT_OPPORTUNITY: "ALERT_OPPORTUNITY",
  CONFIRMED_SAVINGS: "CONFIRMED_SAVINGS",
  NO_SAVINGS_SIGNAL: "NO_SAVINGS_SIGNAL",
  UNKNOWN: "UNKNOWN",
});

export const MIA_SAVINGS_ELIGIBILITY_REASON = Object.freeze({
  VALID_COMPARABLE_PRICES: "VALID_COMPARABLE_PRICES",
  INSUFFICIENT_OFFERS: "INSUFFICIENT_OFFERS",
  INVALID_REFERENCE_PRICE: "INVALID_REFERENCE_PRICE",
  INVALID_COMPARISON_PRICE: "INVALID_COMPARISON_PRICE",
  SAME_PRICE: "SAME_PRICE",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  SHIPPING_UNKNOWN: "SHIPPING_UNKNOWN",
  BASELINE_UNAVAILABLE: "BASELINE_UNAVAILABLE",
  UNVERIFIED_ASSUMPTION: "UNVERIFIED_ASSUMPTION",
  NO_VALID_PRICE: "NO_VALID_PRICE",
  UNKNOWN: "UNKNOWN",
});

export const MIA_SAVINGS_COMPARISON_DIRECTION = Object.freeze({
  REFERENCE_HIGHER: "REFERENCE_HIGHER",
  COMPARISON_HIGHER: "COMPARISON_HIGHER",
  EQUAL: "EQUAL",
  UNKNOWN: "UNKNOWN",
});

export const MIA_SAVINGS_OFFICIAL_CURRENCY = "BRL";
