-- SUPABASE-06 — baseline_catalog_v1
-- Classification: baseline reconciliation (schema)
-- Source: remote public schema dump (read-only, SUPABASE-06)
-- Tables: phone_specs, notebook_specs, product_specs
-- Idempotent: validate-or-create; no DROP/TRUNCATE/DELETE



begin;


CREATE TABLE IF NOT EXISTS "public"."phone_specs" (
    "category" "text",
    "brand" "text",
    "official_name" "text",
    "model_family" "text",
    "aliases" "jsonb",
    "release_year" bigint,
    "release_month" bigint,
    "status" "text",
    "confidence" "text",
    "ram_gb" bigint,
    "storage_gb" bigint,
    "battery_mah" bigint,
    "screen_size_inches" double precision,
    "screen_type" "text",
    "refresh_rate_hz" bigint,
    "chipset" "text",
    "is_5g" boolean,
    "main_camera_mp" numeric,
    "ultrawide_camera_mp" numeric,
    "front_camera_mp" numeric,
    "video_quality" "text",
    "performance_score" bigint,
    "camera_score" bigint,
    "battery_score" bigint,
    "screen_score" bigint,
    "longevity_score" bigint,
    "value_score" bigint,
    "strengths" "text",
    "weaknesses" "text",
    "ideal_for" "text",
    "avoid_if" "text",
    "notes" "text",
    "market_notes" "text",
    "strategic_notes" "text",
    "risk_notes" "text",
    "source_1" "text",
    "source_2" "text",
    "last_verified_at" "text",
    "tier" "text",
    "avg_price_brl" bigint,
    "launch_price_brl" bigint,
    "os_name" "text",
    "os_version_launch" bigint,
    "expected_updates" bigint,
    "security_updates_until" bigint,
    "wireless_charging" boolean,
    "water_resistance" "text",
    "stereo_speakers" boolean,
    "nfc" boolean,
    "esim" boolean,
    "detail_table" "text",
    "detail_id" bigint,
    "id" bigint NOT NULL
);

ALTER TABLE "public"."phone_specs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."phone_specs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."notebook_specs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "category" "text",
    "brand" "text",
    "official_name" "text",
    "model_family" "text",
    "aliases" "text",
    "release_year" integer,
    "status" "text",
    "confidence" "text",
    "cpu" "text",
    "cpu_brand" "text",
    "cpu_family" "text",
    "cpu_generation" "text",
    "gpu" "text",
    "gpu_type" "text",
    "ram_gb" integer,
    "ram_type" "text",
    "upgradeable_ram" boolean,
    "storage_gb" integer,
    "storage_type" "text",
    "upgradeable_storage" boolean,
    "screen_size_inches" numeric,
    "screen_resolution" "text",
    "screen_refresh_rate_hz" integer,
    "panel_type" "text",
    "battery_wh" numeric,
    "weight_kg" numeric,
    "has_backlit_keyboard" boolean,
    "has_fingerprint_reader" boolean,
    "is_gamer" boolean,
    "is_touchscreen" boolean,
    "performance_score" integer,
    "multitask_score" integer,
    "battery_score" integer,
    "screen_score" integer,
    "portability_score" integer,
    "upgrade_score" integer,
    "cooling_score" integer,
    "build_quality_score" integer,
    "longevity_score" integer,
    "value_score" integer,
    "strengths" "text",
    "weaknesses" "text",
    "ideal_for" "text",
    "avoid_if" "text",
    "notes" "text",
    "source_1" "text",
    "source_2" "text",
    "last_verified_at" "date"
);

ALTER TABLE "public"."notebook_specs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notebook_specs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."product_specs" (
    "category" "text",
    "brand" "text",
    "official_name" "text",
    "model_family" "text",
    "aliases" "jsonb",
    "search_text" "text",
    "detail_table" "text",
    "detail_id" bigint,
    "is_active" boolean
);

DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'notebook_specs_pkey'
  ) THEN
    ALTER TABLE ONLY "public"."notebook_specs"
    ADD CONSTRAINT "notebook_specs_pkey" PRIMARY KEY ("id");
  END IF;
END $guard$;

DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'phone_specs_pkey'
  ) THEN
    ALTER TABLE ONLY "public"."phone_specs"
    ADD CONSTRAINT "phone_specs_pkey" PRIMARY KEY ("id");
  END IF;
END $guard$;

DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'unique_phone_name'
  ) THEN
    ALTER TABLE ONLY "public"."phone_specs"
    ADD CONSTRAINT "unique_phone_name" UNIQUE ("official_name");
  END IF;
END $guard$;


-- Catalog security (production-equivalent read policies)
ALTER TABLE public.phone_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notebook_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_specs ENABLE ROW LEVEL SECURITY;

DO $pol$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'phone_specs' AND policyname = 'MIA read phone_specs'
  ) THEN
    CREATE POLICY "MIA read phone_specs" ON public.phone_specs
      FOR SELECT TO authenticated, anon USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'notebook_specs' AND policyname = 'Allow read notebook_specs'
  ) THEN
    CREATE POLICY "Allow read notebook_specs" ON public.notebook_specs
      FOR SELECT TO authenticated, anon USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'product_specs' AND policyname = 'MIA read product_specs'
  ) THEN
    CREATE POLICY "MIA read product_specs" ON public.product_specs
      FOR SELECT TO authenticated, anon USING (true);
  END IF;
END $pol$;



commit;
